### ISSUE TITLE
Migrate date_picker form builder method to ndr_ui

### ISSUE THREAD

**Issue by timgentry** [PublicHealthEngland/ndr_ui#3]
We should add the form builder method for the date picker. This is as far as I got:

``` ruby
module NdrUi
  module Bootstrap
    # Provides a form builder method for the datepicker plugin
    module Datepicker
      # TODO: documentation
      def datepicker_field
        # TODO: migrate implementation
      end
    end
  end
end
```

Therefore we need to:
- create: app/builders/ndr_ui/bootstrap/datepicker.rb
- copy in date_picker, renaming it datepicker_field
- include it in: app/builders/ndr_ui/bootstrap_builder.rb
- test it
- Update the datepicker section of the README

Ideally we would add an [input group](http://getbootstrap.com/components/#input-groups) addon after the text box containing the "calendar" glyphicon.

**Comment by timgentry** [comment]
I don't think it matters that the form builder method is useable even when not including the datepicker js/css.

**Comment by joshpencheon** [comment]
> Ideally we would add an input group addon after the text box containing the "calendar" glyphic.

IIRC, `ndr_ui` doesn't have the `prepend`/`append` options - they haven't been extracted from the original `BootstrapBuilder` yet. Would be another nicely self-contained update.

**Comment by timgentry** [comment]
> IIRC, ndr_ui doesn't have the prepend/append options - they haven't been extracted from the original BootstrapBuilder yet. Would be another nicely self-contained update.

I've created a new issue for this #4
