### ISSUE TITLE
Add BootstrapBuilder prepend/append options

### ISSUE THREAD

**Issue by timgentry** [PublicHealthEngland/ndr_ui#4]
From Josh:

> IIRC, ndr_ui doesn't have the prepend/append options - they haven't been extracted from the original BootstrapBuilder yet. Would be another nicely self-contained update.

**Comment by joshpencheon** [comment]
This should probably tie in with a refactoring of the inline errors - as they're attached directly to the field, they are inside the `input-group`, which can break rendering.

**Comment by suezhou** [comment]
Adding prepend/append add-ons is now a standalone issue.

I added js code which automatically strip off the inner inline errors `.help-block` and attached it outside   `.input-group`.  (commit abae1bb242ba03746e7e362b89b1335288054894)

The js code is currently sitting in `datepicker.js`,  and can be tweaked and moved to a better place once the prepend/append feature availabe.

**Comment by timgentry** [comment]
abae1bb242ba03746e7e362b89b1335288054894 is very much a sticking plaster for the moment. Fixing the symptom, but not the problem. We'll need to remember to revert this once the issue is addressed properly

**Comment by timgentry** [comment]
#6 has now been resolved and the datepicker sticking plaster removed, so this can now go ahead. The datepicker should also be updated to utilise it.

**Comment by timgentry** [comment]
02568fa7e844a5379c1c0eabbd1068704b3094ef resolves this issue
