### ISSUE TITLE
Refactoring of the inline errors

### ISSUE THREAD

**Issue by timgentry** [PublicHealthEngland/ndr_ui#6]
The inline errors need to be less tightly coupled to the input elements, so that append/prepend and other custom input fields can control where the errors are included in the rendered HTML.

**Comment by timgentry** [comment]
Currently we automatically add errors to:

:check_box
:collection_check_boxes
:collection_radio_buttons
:collection_select
:color_field
:datetime_field
:datetime_local_field
:datetime_select
:date_field
:date_select
:email_field
:file_field
:grouped_collection_select
:month_field
:number_field
:password_field
:phone_field
:radio_button
:range_field
:search_field
:select
:telephone_field
:text_area
:text_field
:time_field
:time_select
:time_zone_select
:url_field
:week_field

@joshpencheon, are you happy that we still do that?

**Comment by joshpencheon** [comment]
The annoyance, I think, is that e.g. checkbox collection uses checkbox, and same for radio. However, I think the checkboxes are distinct form attributes, so it doesn't matter if it adds help blocks to the collection as a whole, and each member?

For radio buttons, multiple UI elements share the same form attribute, so I think it only makes sense to have the errors on the collection, not individuals... can't think of a scenario you'd only want a single radio button anyway?!

**Comment by timgentry** [comment]
The commit auto-closed this ticket, so I'm not sure if we need a separate issue for the points you raise @joshpencheon
